### ISSUE TITLE
How can you implement the great smart attribute?!

### ISSUE THREAD

**Issue by eaglexiang** [Snaipe/libcsptr#11]
It's so wonderful that you implement the `smart` type attribute!   
Could you tell me how you did this? I can't find doc related to `user defined type attribute for C/C++`, but only `user defined type`.   
Thank you very much!

**Comment by Snaipe** [comment]
`smart` is just a macro define that expands to `__attribute__((cleanup(sfree_stack)))`. The `cleanup` variable attribute is [https://gcc.gnu.org/onlinedocs/gcc-6.1.0/gcc/Common-Variable-Attributes.html](documented) as calling its parameter on the annotated variable when it goes out of scope.

I've written a more [extensive blog post](https://snai.pe/c/c-smart-pointers/) on the implementations of smart pointers w/ GNU C99, you might want to give it a read.

**Comment by eaglexiang** [comment]
Amazing! I've got the point.   
### thank you once again!
